INSERT INTO site_monitors (
    site_id,
    monitor_type,
    target_url,
    check_interval_seconds,
    expected_status_code,
    body_must_contain,
    body_must_not_contain,
    body_must_contain_texts,
    body_must_not_contain_texts,
    json_path_exists,
    json_path_equals,
    json_path_not_equals,
    max_response_time_ms,
    required_header_name,
    required_header_value,
    header_assertions,
    ssl_certificate_checks_enabled,
    ssl_expiry_warning_days,
    http_check_timeout_seconds_override,
    http_check_max_attempts_override,
    http_check_retry_delays_ms_override,
    is_active,
    last_checked_at,
    last_successful_check_at,
    last_is_success,
    last_status_code,
    last_response_time_ms,
    last_failure_reason,
    last_error_message,
    last_certificate_expires_at,
    last_certificate_days_remaining,
    last_certificate_issuer,
    last_certificate_subject,
    last_certificate_domain,
    created_at,
    updated_at
)
SELECT
    site_id,
    'ssl',
    target_url,
    check_interval_seconds,
    200,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    TRUE,
    ssl_expiry_warning_days,
    http_check_timeout_seconds_override,
    http_check_max_attempts_override,
    http_check_retry_delays_ms_override,
    is_active,
    last_checked_at,
    last_successful_check_at,
    last_is_success,
    NULL,
    NULL,
    last_failure_reason,
    last_error_message,
    last_certificate_expires_at,
    last_certificate_days_remaining,
    last_certificate_issuer,
    last_certificate_subject,
    last_certificate_domain,
    created_at,
    updated_at
FROM site_monitors
WHERE monitor_type = 'http'
  AND ssl_certificate_checks_enabled = TRUE
ON CONFLICT (site_id, monitor_type, target_url) DO NOTHING;

UPDATE site_monitors
SET
    ssl_certificate_checks_enabled = FALSE,
    ssl_expiry_warning_days = NULL,
    last_certificate_expires_at = NULL,
    last_certificate_days_remaining = NULL,
    last_certificate_issuer = NULL,
    last_certificate_subject = NULL,
    last_certificate_domain = NULL,
    updated_at = NOW()
WHERE monitor_type = 'http'
  AND ssl_certificate_checks_enabled = TRUE;
